# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-powershell
# https://github.com/actions/upload-artifact#where-does-the-upload-go
name: PSAppDeployToolkit-Windows-PowerShell
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Display the path
      shell: powershell
      run: echo ${env:PATH}
    - name: Version Display
      shell: powershell
      run: $PSVersionTable
    - name: Azure Login
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # uncomment below to explore what modules/variables/env variables are available in the build image
    # - name: Modules and Variables Display
    #   shell: powershell
    #   run: Get-Module -ListAvailable; (Get-Variable).GetEnumerator() | Sort-Object Name | Out-String; (Get-ChildItem env:*).GetEnumerator() | Sort-Object Name | Out-String
    - name: NuGet Latest
      shell: powershell
      run: Install-PackageProvider -Name "NuGet" -Confirm:$false -Force -Verbose
    - name: PowerShellGet Latest
      shell: powershell
      run: Install-Module -Name PowerShellGet -Repository PSGallery -Force
    - name: Bootstrap
      shell: powershell
      run: ./actions_bootstrap.ps1
    - name: Install .NET Framework 4.6.1 Developer Pack
      shell: powershell
      run: |
        if (!(Test-Path 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1')) {
        $downloadUrl = "https://download.visualstudio.microsoft.com/download/pr/33a48e6c-c0d1-4321-946b-042b92bad691/a9a88bd451286ab9ea015ecc2208d725/ndp461-devpack-kb3105179-enu.exe"
        $downloadPath = "$env:TEMP\ndp461-devpack-kb3105179-enu.exe"
        Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
        Start-Process -FilePath $downloadPath -ArgumentList '/quiet /norestart' -Wait }
    - name: Install AzureSignTool
      run: dotnet tool install --global azuresigntool
    - name: Test and Build
      shell: powershell
      run: Invoke-Build -File .\src\PSAppDeployToolkit.build.ps1
    - name: Upload pester results
      uses: actions/upload-artifact@v4
      with:
        name: pester-results
        path: .\src\Artifacts\testOutput
        if-no-files-found: warn
        overwrite: true
    - name: Upload Module
      uses: actions/upload-artifact@v4
      with:
        name: zip-archive
        path: .\src\Archive
        if-no-files-found: warn
        overwrite: true
